### ISSUE TITLE
discocss-preload.js is put in /tmp/ requiring rerun of discocss every login

### ISSUE THREAD

**Issue by cakePhone** [mlvzk/discocss#24]
Title says it all, discocss-preload.js is under the /tmp/ directory, making me rerun discocss every damn login if I even wanna launch discord. It gives an Error of unknown directory when looking up for the file in /tmp/ if I try running discord without discocss running first.

**Comment by Fasolovic** [comment]
make this executable then change the entry in `/usr/share/applications`                                   

```
#!/bin/bash

discocss &

sleep 5

discord &
```

**Comment by cakePhone** [comment]
I solved it by changing the .desktop entry of discord. Running discocss runs discord so I just changed Exec=discocss

**Comment by cakePhone** [comment]
Closing this
