### ISSUE TITLE
Discord looses the injected CSS after a reboot

### ISSUE THREAD

**Issue by elkowar** [mlvzk/discocss#4]
after each reboot, i need to rerun discocss again to have it apply the theme. Restarting discord does not cause this issue, only a reboot does.
I'm using discord as installed by putting it in `home.packages` in home-manager.

**Comment by 6gk** [comment]
Isn't the proper way of running discord when using this with the `discocss` script? You don't set and forget it, you make this the new launch script.

**Comment by elkowar** [comment]
it does not start up discord for me, so seemingly no

**Comment by 6gk** [comment]
That's odd. Is the binary name of your discord client `discord`/`Discord`?

This is at the end of the script, and it should open one of those...
```command -v discord && exec discord
command -v Discord && exec Discord```

Can you try add
```
set -x
exec 2>&1 > /tmp/log``` to the top of the script (below the top line) then upload /tmp/log here after trying to run it?

**Comment by mlvzk** [comment]
@elkowar how is the discord executable called on your system? It should be running discord automatically

**Comment by 6gk** [comment]
sure
